import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "../assets/index.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CodeNix",
  description: "Generated by create next app",
  icons: [
    { url: "/fav/favicon.ico" },
    { url: "/fav/favicon-32x32.png", sizes: "32x32", type: "image/png" },
    { url: "/fav/android-chrome-192x192.png", sizes: "192x192", type: "image/png" },
    { url: "/fav/android-chrome-512x512.png", sizes: "512x512", type: "image/png" },
    { url: "/fav/apple-touch-icon.png", rel: "apple-touch-icon" },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <div className="h-full pt-25">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
